# This is a basic workflow to help you get started with Actions

name: update github page

env:
  access: restricted
  registry: https://npm.pkg.github.com
  scope: public-ui
  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

on:
  # pull_request:
  #   branches:
  #     - main
  # push:
    # branches-ignore:
    #   - main
  # release:
  #   types:
  #     - released
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: '${{env.registry}}'
          scope: '@${{env.scope}}'
      - name: Clear
        run: |
          rm -rf docs package *.tgz
          ls -la
      - name: Download
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          npm pack @${{env.scope}}/storybook
          ls -la
      - name: Unpack
        run: |
          tar -xzvf public-ui-storybook-*.tgz
          mv package/dist docs
          rm -rf packages *.tgz
          ls -la
      - name: Commit changed files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git status
          git commit -m "Auto update github page"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
