# This is a basic workflow to help you get started with Actions

name: update github page

env:
  scope: public-ui
  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

on:
  push:
  # schedule:
  #   - cron: '0 4 * * *'
  # workflow_call:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{env.scope}}"
      - name: Clear
        run: |
          npm cache clean -f
          rm -rf docs package *.tgz
          ls -la
      # - name: Download storybook
      #   env:
      #     NODE_AUTH_TOKEN: ${{env.token}}
      #   run: |
      #     rm -rf package *.tgz
      #     npm pack @${{env.scope}}/storybook
      #     tar -xzvf public-ui-storybook-*.tgz
      #     mv package/dist docs
      #     ls -la docs
      - name: Download docusaurus
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          rm -rf package *.tgz
          npm pack @${{env.scope}}/docusaurus
          tar -xzvf public-ui-docusaurus-*.tgz
          mv package/build docs
          ls -la docs
      - name: Download designer
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          rm -rf package *.tgz
          npm pack @${{env.scope}}/designer
          tar -xzvf public-ui-designer-*.tgz
          mv package/dist docs/designer
          ls -la docs/designer
      - name: Download slidev
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          rm -rf package *.tgz
          npm pack @${{env.scope}}/slidev
          tar -xzvf public-ui-slidev-*.tgz
          mv package/dist docs/presentation
          ls -la docs/presentation
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          scope: "@${{env.scope}}"
      - name: Download cheat-sheet
        env:
          NODE_AUTH_TOKEN: ${{env.token}}
        run: |
          rm -rf package *.tgz
          npm pack @${{env.scope}}/components
          tar -xzvf public-ui-components-*.tgz
          mv package/cheat-sheet.html docs/cheat-sheet.html
          ls -la docs
      - name: Commit changed files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "Auto update github page"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
